### ISSUE TITLE
[OSPP] Tracking issues: RedisBloom support

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#1696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Currently we intent to support RedisBloom. We separate the task into some subtasks:

1. [x] Support a BloomFilter ( https://github.com/apache/kvrocks/pull/1693 )
2. [x] Support basic `BF.RESERVE`, `BF.ADD`, `BF.EXISTS`.  This is a bit complex, it need to design the structure and metadata of BloomFilter. For simplicity, we can briefly implement only `NOSCALING` first ( https://github.com/apache/kvrocks/pull/1699 )
3. [x] If we only support "EXPANSION" in (2), we need to support "SCALING" ( https://github.com/apache/kvrocks/pull/1721 )
4. [ ] Support Slot migrations
5. [x] Support `BF.CARD` ( https://github.com/apache/kvrocks/pull/1756 )
6. [x] Support `BF.INFO` ( https://github.com/apache/kvrocks/pull/1710 )
7. [x] Support `BF.MADD`  ( https://github.com/apache/kvrocks/pull/1758 )
8. [x] Support `BF.INSERT`
9. [x] Support `BF.MEXIST` ( https://github.com/apache/kvrocks/pull/1756 )

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by mapleFU** [comment]
cc @zncleon

**Comment by zncleon** [comment]
thx a lot, I will commit PRs later.

**Comment by git-hulk** [comment]
@mapleFU Guess we can close this issue now.
