### ISSUE TITLE
Tracking issue: Support RESP3 in Kvrocks

### ISSUE THREAD

**Issue by git-hulk** [apache/kvrocks#1980]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

We would like to support RESP3 even though we know RESP2 won't be abandoned in a short time.
To achieve this, we need to support new types in RESP3 and enable RESP3 in the HELLO command:

- [x] Allow to enable RESP3 in the HELLO command
- [x] #2024 
- [x] #1991
- [x] #2017 
- [x] #2028
- [x] #2034
- [x] #2053
- [x] #2088
- [x] #2102
- [x] #2119
- [x] https://github.com/apache/kvrocks/pull/2130 

Please refer [Redis RESP3](https://github.com/redis/redis-specifications/blob/master/protocol/RESP3.md)
