### ISSUE TITLE
[OSPP 2024] Tracking issues: Enhance Kvrocks Transaction Syntax

### ISSUE THREAD

**Issue by PokIsemaine** [apache/kvrocks#2331]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This issue is about part of the Open Source Promotion Plan(OSPP): Enhance Kvrocks Transaction Syntax
link: https://summer-ospp.ac.cn/org/prodetail/249430512?lang=en&list=pro

This project hopes to attempt to enhance kvrocks transactions in the following areas:
1. Provide complete isolation semantics for single commands
2. Optimize transactions for Multi/Exec and Lua commands
3. Optimize blocking commands such as BLPOP
4. (Optional) Add optimistic transaction mode

Since multiple issues may be involved, we can use this issues to track them uniformly:

In the process of updating, relevant issues and plans will be gradually added.

- [x] https://github.com/apache/kvrocks/issues/2310
- [x] https://github.com/apache/kvrocks/issues/2162
- [ ] Optimize transactions for Multi/Exec commands
- [ ] Optimize blocking commands such as BLPOP
- [ ] (Optional) Add optimistic transaction mode

Anyone is welcome to provide suggestions

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!
