### ISSUE TITLE
Tracking Issue: Support vector search in KQIR

### ISSUE THREAD

**Issue by Beihao-Zhou** [apache/kvrocks#2426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

This includes:
- [x] Implementing vector indexing algorithm, i.e. HNSW & Adding vector indexing support for KQIR Indexer - #2368
- [x] Plan operator & executor for vector indexing - #2434 
- [x] Supporting relevant syntax parsing in front-end languages (SQL, RediSearch query) - #2450 
- [x] Add Optimization Pass, including Index Selection & KnnExpr transformation - #2466 
- [x] Add command to support Hnsw index creation - #2477  
- [x] Documentation on Kvrocks Search - https://github.com/apache/kvrocks-website/pull/241

### Further Steps
- [ ] Improvement for HNSW construction - #2398 
- [ ] Create a const version of HnswIndex that takes a const pointer to HnswVectorFieldMetadata - https://github.com/apache/kvrocks/pull/2434#discussion_r1687707134
- [ ] Support Hybrid Query
- [ ] Improve consistency

### Solution

- #2287
- #2316 

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Would you like to add the encoding format of vector index to https://kvrocks.apache.org/community/kvrocks-search-index-encoding/ when you have time?
