### ISSUE TITLE
Tracking issue: HyperLogLog

### ISSUE THREAD

**Issue by mapleFU** [apache/kvrocks#2454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

Add HyperLogLog for kvrocks

* [x] Dense HLL design: https://github.com/apache/kvrocks-website/pull/207
* [x] Dense HLL PFADD/PFCOUNT: https://github.com/apache/kvrocks/pull/2142
* [x] Dense HLL Merge Support: https://github.com/apache/kvrocks/pull/2457
* [ ] Sparse HLL design
* [ ] Sparse HLL all commands support
* [x] Golang script tests https://github.com/apache/kvrocks/pull/2463
* [ ] Migration tests

### Solution

See https://github.com/apache/kvrocks/discussions/2438

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!
