### ISSUE TITLE
Tracking Issues: Add support for RediSearch Commands

### ISSUE THREAD

**Issue by jonathanc-n** [apache/kvrocks#2555]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/kvrocks/issues) and found no similar issues.

### Motivation

references the tracker issue: #2064 

### FT Commands Implementation Progress

- [x] **FT._LIST**: Returns a list of all existing indexes
- [ ] **FT.AGGREGATE**: Run a search query on an index and perform aggregate transformations on the results
- [ ] **FT.ALIASADD**: Adds an alias to the index
- [ ] **FT.ALIASDEL**: Deletes an alias from the index
- [ ] **FT.ALIASUPDATE**: Adds or updates an alias to the index
#2577 
- [ ] **FT.ALTER**: Adds a new field to the index
- [ ] **FT.CONFIG GET**: Retrieves runtime configuration options
- [ ] **FT.CONFIG SET**: Sets runtime configuration options
- [x] **FT.CREATE**: Creates an index with the given spec
- [ ] **FT.CURSOR DEL**: Deletes a cursor
- [ ] **FT.CURSOR READ**: Reads from a cursor
- [ ] **FT.DICTADD**: Adds terms to a dictionary
- [ ] **FT.DICTDEL**: Deletes terms from a dictionary
- [ ] **FT.DICTDUMP**: Dumps all terms in the given dictionary
- [x] **FT.DROPINDEX**: Deletes the index
- [x] **FT.EXPLAIN**: Returns the execution plan for a complex query
- [ ] **FT.EXPLAINCLI**: Returns the execution plan for a complex query
- [x] **FT.INFO**: Returns information and statistics on the index
- [ ] **FT.PROFILE**: Performs a `FT.SEARCH` or `FT.AGGREGATE` command and collects performance information
- [x] **FT.SEARCH**: Searches the index with a textual query, returning either documents or just ids
- [ ] **FT.SPELLCHECK**: Performs spelling correction on a query, returning suggestions for misspelled terms
- [ ] **FT.SYNDUMP**: Dumps the contents of a synonym group
- [ ] **FT.SYNUPDATE**: Creates or updates a synonym group with additional terms
- [x] **FT.TAGVALS**: Returns the distinct tags indexed in a Tag field
#2564 

FT.SEARCHSQL and FT.EXPLAINSQL has also been additionally implemented in Kvrocks

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by PragmaTwice** [comment]
Thank you for the tracking issue.

However, Kvrocks Search is a relatively large feature and there are so many underlying design and components behind just these commands.

So it's hard to say if a command-level tracking is useful.

**Comment by jonathanc-n** [comment]
@PragmaTwice I guess when proposals/prs come up we can list the issues opened under the commands here. This can act as a tracker for people to know what has been done and is being worked on for Redisearch commands.

**Comment by SharonIV0x86** [comment]
@PragmaTwice @jonathanc-n Is this tracking still open? I am willing to implement support for one of these commands.
